import type { Unit } from '../types';

export const unit02: Unit = {
  id: 'u2',
  n: 2,
  title: 'Who you are, where you are from',
  canDo: 'Say who you are, where you are from, and ask the same of someone else.',
  scenario: 'The second minute of a conversation, after the greeting has landed.',

  grammar: [
    {
      id: 'u2.g.pronouns',
      title: 'Spanish sentences look like they are missing the "I"',
      summary:
        'Subject pronouns (yo, tú, él…) are normally left out. The verb ending already tells you who is doing it, so repeating it is redundant — and sounds oddly emphatic.',
      body: [
        'English verbs barely change: *I speak, you speak, we speak, they speak*. Only "he speaks" differs. Because our endings carry no information, we are forced to prop up every verb with a pronoun.',
        'Spanish endings carry the person outright. *Soy* can only mean "I am". *Eres* can only mean "you are". Adding *yo* or *tú* is possible, but it adds emphasis rather than clarity — like italicising it in English.',
        'So "Soy de Ohio" is the normal way to say "I am from Ohio". "Yo soy de Ohio" means something closer to "*I* am from Ohio (whatever the rest of them are)".',
        'You do need the pronoun when the ending is ambiguous. *Es* covers he, she, and formal you all at once — so if context has not made it obvious, say *él es*, *ella es*, or *usted es*.',
      ],
      examples: [
        { es: 'Soy de Chicago.', en: 'I am from Chicago.', hl: 'Soy' },
        { es: 'Yo soy de Chicago.', en: 'I am from Chicago (as opposed to them).', hl: 'Yo soy' },
        { es: '¿De dónde eres?', en: 'Where are you from?', hl: 'eres' },
        { es: 'Ella es de México.', en: 'She is from Mexico.', hl: 'Ella es' },
      ],
      pitfall:
        'The English-speaker habit is to bolt "yo" onto everything. It is not wrong, but it makes you sound self-centred in a way you cannot hear. Drop it by default.',
    },
    {
      id: 'u2.g.ser',
      title: 'ser — the "is" of identity',
      summary:
        'Spanish splits English "to be" into two verbs. **Ser** is for what something *is*: identity, origin, profession, the essential facts.',
      body: [
        'The forms are irregular and you simply have to own them: **soy** (I am), **eres** (you are, informal), **es** (he/she/it is, and you are formal), **somos** (we are), **son** (they are, and you-plural are).',
        'A textbook from Spain will also list *sois*. In Mexico that form does not exist — *ustedes son* covers every plural "you", formal or not. That is one whole conjugation you never have to learn.',
        'Use ser for: name, origin, nationality, profession, what something is made of, who owns it, and permanent characteristics. "Soy David." "Soy de Ohio." "Es mi esposa." "Es de México."',
        'The irregularity is not random damage. Spanish *ser* is welded together from two different Latin verbs — *esse* (to be) and *sedere* (to sit) — which is why the forms look like they come from different families. They do.',
      ],
      examples: [
        { es: 'Soy David.', en: 'I am David.', hl: 'Soy' },
        { es: '¿De dónde es usted?', en: 'Where are you from? (formal)', hl: 'es' },
        { es: 'Ella es mi esposa.', en: 'She is my wife.', hl: 'es' },
        { es: 'Somos de los Estados Unidos.', en: 'We are from the United States.', hl: 'Somos' },
        { es: 'Ellos son mexicanos.', en: 'They are Mexican.', hl: 'son' },
      ],
      hook: 'From *sedere*, "to sit" — the root of "sedentary", "session", "reside", "president". Ser is the being that *stays put*. Hold that image; the next unit gives you its opposite.',
      pitfall:
        'Do not use ser for how you are feeling or where you are standing. "Soy bien" is not a sentence a Spanish speaker produces — that job belongs to estar, in Unit 3.',
    },
  ],

  items: [
    { id: 'u2.yo', es: 'yo', en: 'I', pos: 'pron', rank: 12, note: 'Only for emphasis — normally left out.' },
    { id: 'u2.tu', es: 'tú', en: 'you (informal)', pos: 'pron', register: 'informal' },
    {
      id: 'u2.usted',
      es: 'usted',
      en: 'you (formal)',
      pos: 'pron',
      register: 'formal',
      hook: 'Compressed from *vuestra merced*, "your mercy". Abbreviated Ud. in writing.',
    },
    { id: 'u2.el', es: 'él', en: 'he', pos: 'pron', note: 'With the accent. *El* without it means "the".' },
    { id: 'u2.ella', es: 'ella', en: 'she', pos: 'pron' },
    { id: 'u2.nosotros', es: 'nosotros', en: 'we', pos: 'pron' },
    {
      id: 'u2.ustedes',
      es: 'ustedes',
      en: 'you all',
      pos: 'pron',
      note: 'Covers every plural "you" in Mexico — formal and informal alike.',
    },
    { id: 'u2.ellos', es: 'ellos', en: 'they', pos: 'pron' },
    { id: 'u2.soy', es: 'soy', en: 'I am', pos: 'verb', rank: 45, note: 'From ser — identity, not mood.' },
    { id: 'u2.eres', es: 'eres', en: 'you are (informal)', pos: 'verb', register: 'informal' },
    {
      id: 'u2.es',
      es: 'es',
      en: 'he/she is',
      enAlt: ['it is', 'you are (formal)', 'he is', 'she is'],
      pos: 'verb',
      rank: 8,
      note: 'Does triple duty: he, she, and formal you.',
    },
    { id: 'u2.somos', es: 'somos', en: 'we are', pos: 'verb' },
    { id: 'u2.son', es: 'son', en: 'they are', enAlt: ['you all are'], pos: 'verb' },
    {
      id: 'u2.de',
      es: 'de',
      en: 'from',
      enAlt: ['of'],
      pos: 'prep',
      rank: 2,
      note: 'The second most common word in Spanish. Means both "of" and "from".',
    },
    {
      id: 'u2.de-donde-es',
      es: '¿de dónde es?',
      en: 'where are you from? (formal)',
      pos: 'phrase',
      register: 'formal',
    },
    { id: 'u2.de-donde-eres', es: '¿de dónde eres?', en: 'where are you from? (informal)', pos: 'phrase', register: 'informal' },
    {
      id: 'u2.estados-unidos',
      es: 'los Estados Unidos',
      en: 'the United States',
      pos: 'noun',
      gender: 'm',
      note: 'Say "soy de los Estados Unidos" — the article stays.',
    },
    {
      id: 'u2.estadounidense',
      es: 'estadounidense',
      en: 'American (from the US)',
      pos: 'adj',
      note: 'The precise word. *Americano* also works but technically covers two continents — and some people will point that out.',
    },
    { id: 'u2.mexicano', es: 'mexicano', en: 'Mexican (man)', pos: 'adj', gender: 'm' },
    { id: 'u2.mexicana', es: 'mexicana', en: 'Mexican (woman)', pos: 'adj', gender: 'f' },
    { id: 'u2.mi', es: 'mi', en: 'my', pos: 'det', rank: 50 },
    { id: 'u2.esposa', es: 'mi esposa', en: 'my wife', pos: 'noun', gender: 'f' },
    { id: 'u2.esposo', es: 'mi esposo', en: 'my husband', pos: 'noun', gender: 'm' },
    {
      id: 'u2.amigo',
      es: 'un amigo',
      en: 'a friend (male)',
      pos: 'noun',
      gender: 'm',
      hook: 'From *amare*, to love — the root of "amiable", "amateur", "amorous".',
    },
    { id: 'u2.amiga', es: 'una amiga', en: 'a friend (female)', pos: 'noun', gender: 'f' },
    {
      id: 'u2.tambien',
      es: 'también',
      en: 'also',
      enAlt: ['too', 'as well'],
      pos: 'adv',
      note: '"Yo también" — "me too" — is a complete and very useful sentence.',
    },
    { id: 'u2.pero', es: 'pero', en: 'but', pos: 'conj', rank: 22 },
    { id: 'u2.y', es: 'y', en: 'and', pos: 'conj', rank: 3 },
  ],

  sentences: [
    { id: 'u2.s1', es: 'Soy de los Estados Unidos.', en: 'I am from the United States.', uses: ['u2.soy', 'u2.de', 'u2.estados-unidos'], cloze: 'Soy' },
    { id: 'u2.s2', es: '¿De dónde es usted?', en: 'Where are you from? (formal)', uses: ['u2.de-donde-es', 'u2.usted'], cloze: '¿De dónde es' },
    { id: 'u2.s3', es: 'Ella es mi esposa.', en: 'She is my wife.', uses: ['u2.ella', 'u2.es', 'u2.esposa'], cloze: 'es' },
    { id: 'u2.s4', es: 'Él es mexicano.', en: 'He is Mexican.', uses: ['u2.el', 'u2.es', 'u2.mexicano'], cloze: 'mexicano' },
    { id: 'u2.s5', es: 'Somos de Chicago.', en: 'We are from Chicago.', uses: ['u2.somos', 'u2.de'], cloze: 'Somos' },
    { id: 'u2.s6', es: 'Mi amiga es de México.', en: 'My friend is from Mexico.', uses: ['u2.amiga', 'u2.es', 'u2.de'], cloze: 'es de' },
    { id: 'u2.s7', es: 'Yo soy estadounidense y ella también.', en: 'I am American and so is she.', uses: ['u2.yo', 'u2.soy', 'u2.estadounidense', 'u2.tambien'], cloze: 'también' },
    { id: 'u2.s8', es: 'No soy de aquí.', en: 'I am not from here.', uses: ['u2.soy', 'u2.de'], cloze: 'No soy' },
    { id: 'u2.s9', es: 'Ellos son mis amigos.', en: 'They are my friends.', uses: ['u2.ellos', 'u2.son', 'u2.amigo'], cloze: 'son' },
    { id: 'u2.s10', es: 'Mucho gusto, soy David.', en: 'Nice to meet you, I am David.', uses: ['u2.soy'], cloze: 'soy' },
  ],
};
