import type { Unit } from '../types.ts';

/**
 * Unit 1 deliberately teaches the conversation-repair phrases ("lifelines") in the
 * very first unit, before numbers, colours, or anything a textbook would open with.
 *
 * Rationale: the goal here is talking with real people. A real conversation does not
 * fail because you lack the word for "purple" — it fails because someone answers at
 * native speed and you have no way to keep the exchange alive. "No entiendo, más
 * despacio por favor" converts a dead end into a slower conversation, which is the
 * single highest-leverage sentence a beginner can own.
 */
export const unit01: Unit = {
  id: 'u1',
  n: 1,
  title: 'Hello, and staying afloat',
  canDo: 'Greet someone, introduce yourself, and rescue a conversation that has gone too fast.',
  scenario: 'Meeting someone for the first time — a neighbour, a host, a shopkeeper.',

  grammar: [
    {
      id: 'u1.g.tu-usted',
      title: 'tú or usted — pick one before you open your mouth',
      summary:
        'Spanish has two words for "you". Use **usted** with strangers, older people, and anyone serving you professionally. Use **tú** with friends, family, children, and peers once invited.',
      body: [
        'English dropped this distinction around 400 years ago (we kept "you" and lost "thou"), so it feels like extra work. It is not optional politeness — it is baked into the verb, and picking wrong is audible.',
        'The safe default for you, travelling in Mexico as an adult, is **usted**. Over-formality reads as respectful. Under-formality with someone older or a stranger reads as presumptuous. Mexicans are notably more formal about this than Spaniards or Argentines.',
        'You will be invited down: if someone says "puedes tutearme" or just starts using tú with you, switch. Until then, usted.',
        'The practical consequence is that most verbs have two "you" forms, and you will learn both. When a phrase in this app is marked *formal*, it is the usted form.',
      ],
      examples: [
        { es: '¿Cómo está usted?', en: 'How are you? (formal)', hl: 'está usted' },
        { es: '¿Cómo estás tú?', en: 'How are you? (informal)', hl: 'estás tú' },
        { es: '¿Cómo se llama usted?', en: "What's your name? (formal)", hl: 'se llama' },
        { es: '¿Cómo te llamas?', en: "What's your name? (informal)", hl: 'te llamas' },
      ],
      hook: '**Usted** is squeezed down from *vuestra merced*, "your mercy" — the same construction as "your honour". You are literally addressing the person as a title, which is why it takes the he/she verb form rather than a "you" form.',
      pitfall:
        'The commonest English-speaker error is not rudeness but inconsistency — opening with usted and drifting into tú mid-conversation. Pick one per person and hold it.',
    },
    {
      id: 'u1.g.greetings',
      title: 'Why it is buenOS días but buenAS tardes',
      summary:
        'Spanish nouns carry a gender, and words attached to them must match. *Día* is masculine (irregularly — it ends in -a), *tarde* and *noche* are feminine.',
      body: [
        'This is your first contact with agreement, which runs through the entire language. You do not need to master it now; you need to notice it exists so it stops looking like a typo.',
        'The greetings are plural for historical reasons nobody agrees on — treat "buenos días / buenas tardes / buenas noches" as three fixed blocks and do not try to derive them.',
        'Switch at the meal, not at the clock. *Buenos días* until the midday meal, *buenas tardes* from then until dark, *buenas noches* after dark. Note that "buenas noches" is both a hello and a goodbye.',
      ],
      examples: [
        { es: 'Buenos días', en: 'Good morning', hl: 'Buenos' },
        { es: 'Buenas tardes', en: 'Good afternoon', hl: 'Buenas' },
        { es: 'Buenas noches', en: 'Good evening / goodnight', hl: 'Buenas' },
      ],
      hook: 'In casual Mexican speech people often just say "**buenas**" on its own — the adjective survives and the noun drops off entirely. Useful to recognise, safe to use.',
      pitfall:
        '*Día* is the trap: it looks feminine and is not. A small set of Greek-derived words ending in -a are masculine — *el día*, *el problema*, *el mapa*, *el idioma*.',
    },
  ],

  pron: {
    id: 'u1.p.vowels',
    title: 'Five vowels, and they never change',
    summary:
      'Spanish has exactly five vowel sounds — a, e, i, o, u — and each is one pure, steady sound. English has around fifteen and slides between them. Fixing this single habit does more for your accent than anything else you will do.',
    body: [
      'Say "no" in English and listen to your mouth: it moves. It starts at "o" and glides toward "oo" — /noʊ/. That glide is a diphthong, and English does it to nearly every long vowel. Spanish does not. Spanish "no" is one locked position, held and released.',
      'The five targets, roughly: **a** as in *father*, **e** as in *bet* (never as in *bay*), **i** as in *machine*, **o** as in *for* (never as in *go*), **u** as in *flute*.',
      'Unstressed vowels also stay pure. English reduces them to a mumble — the "a" in "about" is barely a sound at all. Spanish keeps every vowel at full value, which is why Spanish sounds evenly-paced to English ears. In *banana*, an English speaker says three different vowels; in *plátano*, a Spanish speaker says three clear ones.',
      'Practical drill: say each vowel and hold it for three seconds without letting the sound move. If it wobbles, you are still speaking English.',
    ],
    pairs: [
      { a: 'casa', b: 'cosa', aEn: 'house', bEn: 'thing', contrast: 'a vs o' },
      { a: 'peso', b: 'piso', aEn: 'weight / peso', bEn: 'floor', contrast: 'e vs i' },
      { a: 'pelo', b: 'polo', aEn: 'hair', bEn: 'pole', contrast: 'e vs o' },
      { a: 'muro', b: 'moro', aEn: 'wall', bEn: 'Moor', contrast: 'u vs o' },
    ],
  },

  items: [
    {
      id: 'u1.hola',
      es: 'hola',
      en: 'hello',
      pos: 'interj',
      rank: 1,
      register: 'neutral',
      hook: 'Same instinct as English "holler" and old "hallo" — a shout to turn someone toward you. The h is silent, always: "OH-la".',
    },
    {
      id: 'u1.buenos-dias',
      es: 'buenos días',
      en: 'good morning',
      pos: 'phrase',
      literal: 'good days',
      rank: 2,
      hook: '*Bueno* is the root of "bonus", "bounty", "bona fide". *Día* is the root of "diary", "diurnal", "journal".',
    },
    {
      id: 'u1.buenas-tardes',
      es: 'buenas tardes',
      en: 'good afternoon',
      pos: 'phrase',
      literal: 'good afternoons',
      hook: '*Tarde* means both "afternoon" and "late" — the same root as English "tardy".',
    },
    {
      id: 'u1.buenas-noches',
      es: 'buenas noches',
      en: 'good evening',
      enAlt: ['goodnight', 'good night'],
      pos: 'phrase',
      literal: 'good nights',
      note: 'Works as both a greeting and a farewell after dark.',
      hook: '*Noche* is the root of "nocturnal" and "equinox".',
    },
    {
      id: 'u1.como-esta',
      es: '¿cómo está?',
      en: 'how are you? (formal)',
      pos: 'phrase',
      register: 'formal',
      rank: 40,
      note: 'Your default with strangers. Add "usted" for extra weight: ¿cómo está usted?',
    },
    {
      id: 'u1.como-estas',
      es: '¿cómo estás?',
      en: 'how are you? (informal)',
      pos: 'phrase',
      register: 'informal',
      note: 'For friends, family, and anyone who has used tú with you first.',
    },
    {
      id: 'u1.bien',
      es: 'bien',
      en: 'well',
      enAlt: ['fine', 'good'],
      pos: 'adv',
      rank: 35,
      hook: 'The *bene-* of "benefit", "benevolent", "benign". "Bien, gracias" is the whole answer — no verb needed.',
    },
    {
      id: 'u1.gracias',
      es: 'gracias',
      en: 'thank you',
      enAlt: ['thanks'],
      pos: 'interj',
      rank: 30,
      hook: 'Same root as "gratitude", "gracious", "grateful". Literally "graces" — plural.',
    },
    {
      id: 'u1.de-nada',
      es: 'de nada',
      en: "you're welcome",
      pos: 'phrase',
      literal: 'of nothing',
      hook: '*Nada* is literally "a thing born". Latin said *nulla res nata* — "no born thing" — and Spanish kept only the last word, which absorbed the whole negative. Same root as "native", "nascent" and "nature".',
    },
    {
      id: 'u1.por-favor',
      es: 'por favor',
      en: 'please',
      pos: 'phrase',
      literal: 'for favour',
      rank: 25,
    },
    { id: 'u1.si', es: 'sí', en: 'yes', pos: 'adv', rank: 20, note: 'With the accent. *Si* without it means "if".' },
    { id: 'u1.no', es: 'no', en: 'no', enAlt: ['not'], pos: 'adv', rank: 5 },
    {
      id: 'u1.me-llamo',
      es: 'me llamo',
      en: 'my name is',
      pos: 'phrase',
      literal: 'I call myself',
      rank: 60,
      hook: '*Llamar* is the root of "clamour" and "proclaim" — to call out. The ll is a soft y sound in Mexico: "may YAH-mo".',
    },
    {
      id: 'u1.como-te-llamas',
      es: '¿cómo te llamas?',
      en: "what's your name? (informal)",
      pos: 'phrase',
      literal: 'how do you call yourself?',
      register: 'informal',
    },
    {
      id: 'u1.como-se-llama',
      es: '¿cómo se llama?',
      en: "what's your name? (formal)",
      pos: 'phrase',
      register: 'formal',
      note: 'The one to use with a stranger.',
    },
    {
      id: 'u1.mucho-gusto',
      es: 'mucho gusto',
      en: 'nice to meet you',
      pos: 'phrase',
      literal: 'much pleasure',
      hook: '*Gusto* is the root of "gusto", "disgust", "gustatory" — taste, and by extension pleasure.',
    },
    {
      id: 'u1.y-usted',
      es: '¿y usted?',
      en: 'and you? (formal)',
      pos: 'phrase',
      register: 'formal',
      note: 'Bouncing the question back is the whole trick to sounding conversational rather than interrogated.',
    },
    {
      id: 'u1.adios',
      es: 'adiós',
      en: 'goodbye',
      pos: 'interj',
      literal: 'to God',
      hook: 'Identical construction to French *adieu* — a shortened blessing. Slightly final; for everyday partings Mexicans prefer "hasta luego".',
    },
    {
      id: 'u1.hasta-luego',
      es: 'hasta luego',
      en: 'see you later',
      pos: 'phrase',
      literal: 'until later',
      hook: '*Hasta* came into Spanish from Arabic *ḥattā* — one of roughly 4,000 Arabic loanwords from the 800 years of Al-Andalus.',
    },
    {
      id: 'u1.senor',
      es: 'señor',
      en: 'sir',
      enAlt: ['mr', 'mister'],
      pos: 'noun',
      gender: 'm',
      hook: 'Literally "the elder" — the root of "senior", "senate", "senile". French *monsieur* and English "sire" are the same word.',
    },
    { id: 'u1.senora', es: 'señora', en: "ma'am", enAlt: ['mrs', 'madam'], pos: 'noun', gender: 'f' },
    {
      id: 'u1.disculpe',
      es: 'disculpe',
      en: 'excuse me',
      pos: 'phrase',
      register: 'formal',
      note: 'To get a stranger\'s attention before asking anything. Start every request with it.',
      hook: '*Culpa* is blame — the root of "culpable", "exculpate", and "mea culpa". You are asking to be un-blamed.',
      lifeline: true,
    },
    {
      id: 'u1.perdon',
      es: 'perdón',
      en: 'sorry',
      enAlt: ['pardon', 'excuse me'],
      pos: 'interj',
      note: 'For apologising, or for squeezing past someone.',
      lifeline: true,
    },
    {
      id: 'u1.no-entiendo',
      es: 'no entiendo',
      en: "I don't understand",
      pos: 'phrase',
      rank: 200,
      note: 'Learn this before anything else you might want to say.',
      hook: '*Entender* is from Latin *intendere*, "to stretch toward" — the same root as "intend" and "attention". Understanding as reaching toward something.',
      lifeline: true,
    },
    {
      id: 'u1.mas-despacio',
      es: 'más despacio, por favor',
      en: 'slower, please',
      pos: 'phrase',
      literal: 'more slowly, please',
      note: 'The most useful sentence in this entire app. Native speakers will slow down; they simply cannot tell they were fast.',
      lifeline: true,
    },
    {
      id: 'u1.puede-repetir',
      es: '¿puede repetir?',
      en: 'can you repeat that?',
      pos: 'phrase',
      register: 'formal',
      lifeline: true,
    },
    {
      id: 'u1.como-se-dice',
      es: '¿cómo se dice...?',
      en: 'how do you say...?',
      pos: 'phrase',
      note: 'Point at the thing and say this. It turns any stranger into a teacher.',
      lifeline: true,
    },
    {
      id: 'u1.habla-ingles',
      es: '¿habla inglés?',
      en: 'do you speak English?',
      pos: 'phrase',
      register: 'formal',
      note: 'The escape hatch. Try Spanish first — using it usually earns more patience than skipping it.',
      lifeline: true,
    },
  ],

  sentences: [
    {
      id: 'u1.s1',
      es: 'Hola, me llamo Ana.',
      en: 'Hello, my name is Ana.',
      uses: ['u1.hola', 'u1.me-llamo'],
      cloze: 'me llamo',
    },
    {
      id: 'u1.s2',
      es: 'Buenos días, señora.',
      en: 'Good morning, ma\'am.',
      uses: ['u1.buenos-dias', 'u1.senora'],
      cloze: 'Buenos días',
    },
    {
      id: 'u1.s3',
      es: 'Disculpe, ¿cómo se llama?',
      en: "Excuse me, what's your name?",
      uses: ['u1.disculpe', 'u1.como-se-llama'],
      cloze: 'Disculpe',
    },
    {
      id: 'u1.s4',
      es: 'Mucho gusto, señor.',
      en: 'Nice to meet you, sir.',
      uses: ['u1.mucho-gusto', 'u1.senor'],
      cloze: 'Mucho gusto',
    },
    {
      id: 'u1.s5',
      es: 'Bien, gracias. ¿Y usted?',
      en: 'Fine, thank you. And you?',
      uses: ['u1.bien', 'u1.gracias', 'u1.y-usted'],
      cloze: '¿Y usted?',
    },
    {
      id: 'u1.s6',
      es: 'No entiendo. Más despacio, por favor.',
      en: "I don't understand. Slower, please.",
      uses: ['u1.no-entiendo', 'u1.mas-despacio'],
      cloze: 'No entiendo',
    },
    {
      id: 'u1.s7',
      es: 'Disculpe, ¿habla inglés?',
      en: 'Excuse me, do you speak English?',
      uses: ['u1.disculpe', 'u1.habla-ingles'],
      cloze: '¿habla inglés?',
    },
    {
      id: 'u1.s8',
      es: 'Buenas noches. Hasta luego.',
      en: 'Good evening. See you later.',
      uses: ['u1.buenas-noches', 'u1.hasta-luego'],
      cloze: 'Hasta luego',
    },
    {
      id: 'u1.s9',
      es: 'Gracias. — De nada.',
      en: 'Thank you. — You\'re welcome.',
      uses: ['u1.gracias', 'u1.de-nada'],
      cloze: 'De nada',
    },
    {
      id: 'u1.s10',
      es: '¿Cómo se dice "water"?',
      en: 'How do you say "water"?',
      uses: ['u1.como-se-dice'],
      cloze: '¿Cómo se dice',
    },
  ],
};
